######################################################################
# Automatically generated by qmake (2.01a) Wed Jan 2 09:44:13 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
