######################################################################
# Automatically generated by qmake (2.01a) Mon Oct 8 18:39:24 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
