######################################################################
# Automatically generated by qmake (2.01a) Sun Jul 1 15:31:55 2012
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

CONFIG = -qt
# Input
SOURCES += main.c
