######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 18 22:07:59 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += entab.h esettab.h tabpos.h deltab.h
SOURCES += entab.c esettab.c main.c tabpos.c deltab.c
