######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 25 09:36:35 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += comment.h getword.h tnode.h
SOURCES += comment.c getword.c main.c tnode.c
