######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 7 20:53:22 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += getch.h
SOURCES += getch.c main.c
