######################################################################
# Automatically generated by qmake (2.01a) Sun Jul 1 15:27:26 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG -= qt
CONFIG += console

# Input
SOURCES += main.c
