######################################################################
# Automatically generated by qmake (2.01a) Mon Oct 15 13:22:09 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
