#############################################################################
# Makefile for building: c-programming-language
# Generated by qmake (2.01a) (Qt 4.8.3) on: Wed Nov 7 20:08:38 2012
# Project:  c-programming-language.pro
# Template: subdirs
# Command: /usr/bin/qmake -o Makefile c-programming-language.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-chap01 \
		sub-chap02 \
		sub-chap03 \
		sub-chap04

chap01/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) chap01/ || $(MKDIR) chap01/ 
	cd chap01/ && $(QMAKE) /home/rice/workspace/c-programming-language/chap01/chap01.pro -o $(MAKEFILE)
sub-chap01-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) chap01/ || $(MKDIR) chap01/ 
	cd chap01/ && $(QMAKE) /home/rice/workspace/c-programming-language/chap01/chap01.pro -o $(MAKEFILE)
sub-chap01: chap01/$(MAKEFILE) FORCE
	cd chap01/ && $(MAKE) -f $(MAKEFILE)
sub-chap01-make_default: chap01/$(MAKEFILE) FORCE
	cd chap01/ && $(MAKE) -f $(MAKEFILE) 
sub-chap01-make_first: chap01/$(MAKEFILE) FORCE
	cd chap01/ && $(MAKE) -f $(MAKEFILE) first
sub-chap01-all: chap01/$(MAKEFILE) FORCE
	cd chap01/ && $(MAKE) -f $(MAKEFILE) all
sub-chap01-clean: chap01/$(MAKEFILE) FORCE
	cd chap01/ && $(MAKE) -f $(MAKEFILE) clean
sub-chap01-distclean: chap01/$(MAKEFILE) FORCE
	cd chap01/ && $(MAKE) -f $(MAKEFILE) distclean
sub-chap01-install_subtargets: chap01/$(MAKEFILE) FORCE
	cd chap01/ && $(MAKE) -f $(MAKEFILE) install
sub-chap01-uninstall_subtargets: chap01/$(MAKEFILE) FORCE
	cd chap01/ && $(MAKE) -f $(MAKEFILE) uninstall
chap02/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) chap02/ || $(MKDIR) chap02/ 
	cd chap02/ && $(QMAKE) /home/rice/workspace/c-programming-language/chap02/chap02.pro -o $(MAKEFILE)
sub-chap02-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) chap02/ || $(MKDIR) chap02/ 
	cd chap02/ && $(QMAKE) /home/rice/workspace/c-programming-language/chap02/chap02.pro -o $(MAKEFILE)
sub-chap02: chap02/$(MAKEFILE) FORCE
	cd chap02/ && $(MAKE) -f $(MAKEFILE)
sub-chap02-make_default: chap02/$(MAKEFILE) FORCE
	cd chap02/ && $(MAKE) -f $(MAKEFILE) 
sub-chap02-make_first: chap02/$(MAKEFILE) FORCE
	cd chap02/ && $(MAKE) -f $(MAKEFILE) first
sub-chap02-all: chap02/$(MAKEFILE) FORCE
	cd chap02/ && $(MAKE) -f $(MAKEFILE) all
sub-chap02-clean: chap02/$(MAKEFILE) FORCE
	cd chap02/ && $(MAKE) -f $(MAKEFILE) clean
sub-chap02-distclean: chap02/$(MAKEFILE) FORCE
	cd chap02/ && $(MAKE) -f $(MAKEFILE) distclean
sub-chap02-install_subtargets: chap02/$(MAKEFILE) FORCE
	cd chap02/ && $(MAKE) -f $(MAKEFILE) install
sub-chap02-uninstall_subtargets: chap02/$(MAKEFILE) FORCE
	cd chap02/ && $(MAKE) -f $(MAKEFILE) uninstall
chap03/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) chap03/ || $(MKDIR) chap03/ 
	cd chap03/ && $(QMAKE) /home/rice/workspace/c-programming-language/chap03/chap03.pro -o $(MAKEFILE)
sub-chap03-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) chap03/ || $(MKDIR) chap03/ 
	cd chap03/ && $(QMAKE) /home/rice/workspace/c-programming-language/chap03/chap03.pro -o $(MAKEFILE)
sub-chap03: chap03/$(MAKEFILE) FORCE
	cd chap03/ && $(MAKE) -f $(MAKEFILE)
sub-chap03-make_default: chap03/$(MAKEFILE) FORCE
	cd chap03/ && $(MAKE) -f $(MAKEFILE) 
sub-chap03-make_first: chap03/$(MAKEFILE) FORCE
	cd chap03/ && $(MAKE) -f $(MAKEFILE) first
sub-chap03-all: chap03/$(MAKEFILE) FORCE
	cd chap03/ && $(MAKE) -f $(MAKEFILE) all
sub-chap03-clean: chap03/$(MAKEFILE) FORCE
	cd chap03/ && $(MAKE) -f $(MAKEFILE) clean
sub-chap03-distclean: chap03/$(MAKEFILE) FORCE
	cd chap03/ && $(MAKE) -f $(MAKEFILE) distclean
sub-chap03-install_subtargets: chap03/$(MAKEFILE) FORCE
	cd chap03/ && $(MAKE) -f $(MAKEFILE) install
sub-chap03-uninstall_subtargets: chap03/$(MAKEFILE) FORCE
	cd chap03/ && $(MAKE) -f $(MAKEFILE) uninstall
chap04/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) chap04/ || $(MKDIR) chap04/ 
	cd chap04/ && $(QMAKE) /home/rice/workspace/c-programming-language/chap04/chap04.pro -o $(MAKEFILE)
sub-chap04-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) chap04/ || $(MKDIR) chap04/ 
	cd chap04/ && $(QMAKE) /home/rice/workspace/c-programming-language/chap04/chap04.pro -o $(MAKEFILE)
sub-chap04: chap04/$(MAKEFILE) FORCE
	cd chap04/ && $(MAKE) -f $(MAKEFILE)
sub-chap04-make_default: chap04/$(MAKEFILE) FORCE
	cd chap04/ && $(MAKE) -f $(MAKEFILE) 
sub-chap04-make_first: chap04/$(MAKEFILE) FORCE
	cd chap04/ && $(MAKE) -f $(MAKEFILE) first
sub-chap04-all: chap04/$(MAKEFILE) FORCE
	cd chap04/ && $(MAKE) -f $(MAKEFILE) all
sub-chap04-clean: chap04/$(MAKEFILE) FORCE
	cd chap04/ && $(MAKE) -f $(MAKEFILE) clean
sub-chap04-distclean: chap04/$(MAKEFILE) FORCE
	cd chap04/ && $(MAKE) -f $(MAKEFILE) distclean
sub-chap04-install_subtargets: chap04/$(MAKEFILE) FORCE
	cd chap04/ && $(MAKE) -f $(MAKEFILE) install
sub-chap04-uninstall_subtargets: chap04/$(MAKEFILE) FORCE
	cd chap04/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: c-programming-language.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile c-programming-language.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile c-programming-language.pro

qmake_all: sub-chap01-qmake_all sub-chap02-qmake_all sub-chap03-qmake_all sub-chap04-qmake_all FORCE

make_default: sub-chap01-make_default sub-chap02-make_default sub-chap03-make_default sub-chap04-make_default FORCE
make_first: sub-chap01-make_first sub-chap02-make_first sub-chap03-make_first sub-chap04-make_first FORCE
all: sub-chap01-all sub-chap02-all sub-chap03-all sub-chap04-all FORCE
clean: sub-chap01-clean sub-chap02-clean sub-chap03-clean sub-chap04-clean FORCE
	-$(DEL_FILE) ${TARGET}
distclean: sub-chap01-distclean sub-chap02-distclean sub-chap03-distclean sub-chap04-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-chap01-install_subtargets sub-chap02-install_subtargets sub-chap03-install_subtargets sub-chap04-install_subtargets FORCE
uninstall_subtargets: sub-chap01-uninstall_subtargets sub-chap02-uninstall_subtargets sub-chap03-uninstall_subtargets sub-chap04-uninstall_subtargets FORCE

sub-chap01-check: chap01/$(MAKEFILE)
	cd chap01/ && $(MAKE) -f $(MAKEFILE) check
sub-chap02-check: chap02/$(MAKEFILE)
	cd chap02/ && $(MAKE) -f $(MAKEFILE) check
sub-chap03-check: chap03/$(MAKEFILE)
	cd chap03/ && $(MAKE) -f $(MAKEFILE) check
sub-chap04-check: chap04/$(MAKEFILE)
	cd chap04/ && $(MAKE) -f $(MAKEFILE) check
check: sub-chap01-check sub-chap02-check sub-chap03-check sub-chap04-check
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

