#############################################################################
# Makefile for building: cuda-by-example
# Generated by qmake (2.01a) (Qt 4.8.2) on: Tue Sep 18 21:35:27 2012
# Project:  cuda-by-example.pro
# Template: subdirs
# Command: /usr/bin/qmake -o Makefile cuda-by-example.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-chap03

chap03/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) chap03/ || $(MKDIR) chap03/ 
	cd chap03/ && $(QMAKE) /home/rice/workspace/cuda-by-example/chap03/chap03.pro -o $(MAKEFILE)
sub-chap03-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) chap03/ || $(MKDIR) chap03/ 
	cd chap03/ && $(QMAKE) /home/rice/workspace/cuda-by-example/chap03/chap03.pro -o $(MAKEFILE)
sub-chap03: chap03/$(MAKEFILE) FORCE
	cd chap03/ && $(MAKE) -f $(MAKEFILE)
sub-chap03-make_default: chap03/$(MAKEFILE) FORCE
	cd chap03/ && $(MAKE) -f $(MAKEFILE) 
sub-chap03-make_first: chap03/$(MAKEFILE) FORCE
	cd chap03/ && $(MAKE) -f $(MAKEFILE) first
sub-chap03-all: chap03/$(MAKEFILE) FORCE
	cd chap03/ && $(MAKE) -f $(MAKEFILE) all
sub-chap03-clean: chap03/$(MAKEFILE) FORCE
	cd chap03/ && $(MAKE) -f $(MAKEFILE) clean
sub-chap03-distclean: chap03/$(MAKEFILE) FORCE
	cd chap03/ && $(MAKE) -f $(MAKEFILE) distclean
sub-chap03-install_subtargets: chap03/$(MAKEFILE) FORCE
	cd chap03/ && $(MAKE) -f $(MAKEFILE) install
sub-chap03-uninstall_subtargets: chap03/$(MAKEFILE) FORCE
	cd chap03/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: cuda-by-example.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile cuda-by-example.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile cuda-by-example.pro

qmake_all: sub-chap03-qmake_all FORCE

make_default: sub-chap03-make_default FORCE
make_first: sub-chap03-make_first FORCE
all: sub-chap03-all FORCE
clean: sub-chap03-clean FORCE
	-$(DEL_FILE) ${TARGET}
distclean: sub-chap03-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-chap03-install_subtargets FORCE
uninstall_subtargets: sub-chap03-uninstall_subtargets FORCE

sub-chap03-check: chap03/$(MAKEFILE)
	cd chap03/ && $(MAKE) -f $(MAKEFILE) check
check: sub-chap03-check
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

