######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 25 10:39:48 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += debug

# Input
HEADERS += comment.h getword.h nlist.h
SOURCES += comment.c getword.c main.c nlist.c
