######################################################################
# Automatically generated by qmake (2.01a) Mon Oct 8 19:05:05 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += debug

# Input
SOURCES += main.c
