######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 7 18:22:18 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
