######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 7 21:27:45 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
