######################################################################
# Automatically generated by qmake (2.01a) Wed Jan 2 09:44:13 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += util.h vector.h
SOURCES += main.c util.c vector.c
