######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 14 09:13:00 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
