######################################################################
# Automatically generated by qmake (2.01a) Sat Oct 13 17:53:19 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
