######################################################################
# Automatically generated by qmake (2.01a) Wed Oct 10 12:45:59 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
