######################################################################
# Automatically generated by qmake (2.01a) Mon Oct 15 17:09:41 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += getch.h getop.h stack.h mygetline.h
SOURCES += getch.c getop.c main.c stack.c mygetline.c
