######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 13 21:00:51 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QMAKE_CFLAGS_RELEASE += -std=c90
QMAKE_CFLAGS_DEBUG += -ansi

# Input
SOURCES += main.c
