######################################################################
# Automatically generated by qmake (2.01a) Sat Nov 24 11:10:38 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += debug

# Input
HEADERS += getword.h tnode.h comment.h
SOURCES += getword.c main.c tnode.c comment.c
