######################################################################
# Automatically generated by qmake (2.01a) Fri Oct 12 22:26:25 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
