######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 18 16:51:00 2012
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += tabpos.h settab.h
SOURCES += main.c tabpos.c settab.c
