######################################################################
# Automatically generated by qmake (2.01a) Wed Oct 10 10:49:03 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
