######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 25 14:18:49 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
