######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 13 21:00:51 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
