######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 21 19:35:42 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c

QMAKE_CC = '~/.vim/bundle/clang_complete/bin/cc_args.py gcc'
