######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 25 11:35:46 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
