######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 25 22:04:50 2012
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += chap03
