######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 18 15:27:35 2012
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += debug

# Input
HEADERS += getop.h ungets.h stack.h
SOURCES += getop.c main.c ungets.c stack.c
