######################################################################
# Automatically generated by qmake (2.01a) Sat Nov 24 09:55:39 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += comment.h getword.h tnode.h
SOURCES += comment.c getword.c main.c tnode.c
