######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 7 16:46:24 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
