######################################################################
# Automatically generated by qmake (2.01a) Tue Sep 18 18:58:07 2012
######################################################################

TEMPLATE = subdirs

# Input
SUBDIRS = hello  cu-hello add dev-prop choose-dev
