######################################################################
# Automatically generated by qmake (2.01a) Mon Oct 15 11:12:11 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
