######################################################################
# Automatically generated by qmake (2.01a) Wed Jan 2 09:42:14 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . 01 02 03 04 assign01
INCLUDEPATH += .

# Input
SOURCES += 01/main.c 02/main.c 03/main.c 04/main.c assign01/main.c
