######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 22 08:11:12 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
