######################################################################
# Automatically generated by qmake (2.01a) Wed Oct 10 13:43:54 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += debug
# Input
SOURCES += main.c
