######################################################################
# Automatically generated by qmake (2.01a) Sat Oct 13 16:34:50 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
