######################################################################
# Automatically generated by qmake (2.01a) Fri Nov 23 13:21:13 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dcl.h dirdcl.h errmsg.h gettoken.h global.h nexttoken.h
SOURCES += dcl.c dirdcl.c errmsg.c gettoken.c global.c main.c nexttoken.c
